### ISSUE TITLE
Generation of care schedule

### ISSUE THREAD

**Issue by Inn0** [ivansdivans/bloom-buddy-mobile#11]
# To implement
- [ ] A user can generate a care schedule for their household from the care schedule screen (a button to generate a care schedule is presented if no care schedule has been generated yet)
    - [ ] A user can select what plants should be taking into consideration for the care schedule when generating it.
    - [ ] Local weather data and household data (light, humidity, etc.) is taken into consideration.
    - [ ] A care schedule includes to-do items that are recurring (e.g.: water plant X every 3 days)

**Comment by ivansdivans** [comment]
We should remember to show for which plant the todo is in carescheduleview. Thought about it yesterday :)

**Comment by Inn0** [comment]
Agreed, IMO the care schedule would use the plant nicknames. For example if you have a tulip called Philip, the care schedule should include "Water Philip", "Repot Philip", etc.
