### ISSUE TITLE
Implement care schedule screen

### ISSUE THREAD

**Issue by Inn0** [ivansdivans/bloom-buddy-mobile#9]
# To implement
- [x] A user can navigate to their household's care schedule.
- [x] The care schedule is presented in a calendar-like format.
- [x] The care schedule has daily to-do items.
- [ ] The days in the care schedule are colored from red to green, based on care-taking (= daily to-do items) progress.

**Comment by ivansdivans** [comment]
[Useful link](https://medium.com/@alidinbinabdulmalik/a-simple-guide-to-using-viewmodel-94118b39e940) about viewModels in SwiftUI screens
